### ISSUE TITLE
Image will not parse with the format ![](http://some.url)

### ISSUE THREAD

**Issue by TakWolf** [lruiz/MarkdownPapers#50]
I have use the version 1.4.3 and I found that image will not parse with the format : 

` ![](https://some.url)      // will not parse`

it can be parse with the format : 

` ![alt](https://some.url)      // can parse`

Empty alt for image should be parse I think, this may be a bug.

**Comment by TakWolf** [comment]
@lruiz  

thanks for fix it, I do not find 1.4.4 in maven center, when the new version can be released?

**Comment by lruiz** [comment]
Hi, It was released a few moments ago, It will take a couple of hours to arrive to maven center
